# Generated by Django 2.1.5 on 2019-01-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urun_kodu', models.CharField(max_length=25)),
                ('adet', models.IntegerField()),
                ('son_kullanma', models.CharField(max_length=3)),
                ('kategori', models.FloatField()),
            ],
        ),
    ]
